# Generated by Django 3.2.3 on 2021-06-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='employee_pictures')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.department')),
            ],
        ),
    ]
