# Generated by Django 3.2.3 on 2021-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='cnic',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
